version: 0.1
phases:
  pre_build:
    commands:
      - BUILD_PROJECT_NAME=DotStepStarter
  build:
    commands:
      - dotnet build $BUILD_PROJECT_NAME
      - dotnet publish -c release $BUILD_PROJECT_NAME
  post_build:
    commands:
      - dotnet new console --name Builder
      - sed -i 's/Console.WriteLine("Hello World!")/DotStep.Builder.DotStepBuilder.BuildTemplate(args[0])/g' Builder/Program.cs
      - cd Builder && dotnet add package DotStep.Builder && dotnet build && dotnet bin/Debug/netcoreapp2.0/Builder.dll ../DotStepStarter/bin/Debug/netcoreapp2.0/
artifacts:
  files:
    - $BUILD_PROJECT_NAME/bin/release/netcoreapp2.0/publish/**/*
  discard-paths: yes